name: Build & Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    AUTH_MODE: "none"
    APP_MODE: "ci"

jobs:
    frontend-ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@95c693f66ff8664cf1be27889f7b41eb6fff6a8f #v10
