name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: ./.github/actions/docker-build
        with:
          working-directory: .
          ghcr-enabled: true
          quay-enabled: false
          image-name: "textmate-client"
          vulnerability-scan: false
          push: ${{ contains(github.ref, 'tags/v') }}
          dcc-bs-token: ${{ secrets.DCC_BS_TOKEN }}
